project_name: "fm"

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./main.go
    binary: fm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarm: "7"

archives:
  - format_overrides:
      - goos: windows
        format: zip

nfpms:
  - maintainer: Tyler Knipfer <knipferrc@gmail.com>
    description: FM is a simple, configurable, and fun to use file manager
    homepage: https://github.com/knipferrc/fm
    license: MIT
    formats:
      - deb
      - rpm
      - apk

scoop:
  bucket:
    owner: knipferrc
    name: scoop-bucket
    branch: main
    token: "{{ .Env.ACTIONS_TOKEN }}"
  commit_author:
    name: goreleaserbot
    email: bot@goreleaser.com
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  description: "A terminal based file manager"
  license: MIT
  pre_install: ["Write-Host 'Running preinstall command'"]
  post_install: ["Write-Host 'Running postinstall command'"]
